#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ ( "$SHELL" = "/bin/bash" && -o interactive ) && ( -s "${ZDOTDIR:-$HOME}/.zprofile" && "$TERMINATOR_UUID" != "" ) ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
