#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export WORKON_HOME=~/.virtualenvs
mkdir -p $WORKON_HOME
test -f /usr/local/bin/virtualenvwrapper.sh && source /usr/local/bin/virtualenvwrapper.sh
test -f /usr/share/virtualenvwrapper/virtualenvwrapper.sh && source /usr/share/virtualenvwrapper/virtualenvwrapper.sh

test -f ${HOME}/.gitsubrepo/.rc && source ${HOME}/.gitsubrepo/.rc

if [ "${SSH_AGENT_PID}" = "" -a "${SSH_AUTH_SOCK}" = "" ]
then
    eval `ssh-agent`
fi
