#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export WORKON_HOME=~/.virtualenvs
mkdir -p $WORKON_HOME
source /usr/local/bin/virtualenvwrapper.sh

export CVSROOT=":pserver:bdunandlaisin@tigre_nis:/home/dev/cvsroot"

source ${HOME}/.gitsubrepo/.rc

if [ "${SSH_AGENT_PID}" = "" ]
then
    eval `ssh-agent`
fi
